language: node_js
node_js:
  - "stable"
script:
  - npm run build
  - npm test
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $github_token
  on:
    branch: main
notifications:
  slack: is-tp3:nkCXTVx7Ohsbhtuo5OsxsVBI
addons:
  sonarcloud: 
    organization: 'enzostefani507'
    token: 6c5f3ef0e8de37c5a21ac66f3ba1d6e1eff61b91