language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
  - npm test
  - sonar-scanner
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $github_token
  on:
    branch: main
notifications:
  slack: is-tp3:nkCXTVx7Ohsbhtuo5OsxsVBI
addons:
  sonarcloud:
    organization: "enzostefani507" # the key of the org you chose at step #3
    token:
      secure: "80e67d75a2c523f1a2f1ead8b94f521d83e4573c" # encrypted value of your token
git:
  depth: false